In [1]:
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings("ignore")

# Loading the dataset

In [207]:
df = pd.read_csv("car_prices.csv")

In [208]:
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [210]:
df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [211]:
df.shape

(558837, 16)

# DATA CLEANING AND PREPROCESSING

In [212]:
df.columns

Index(['year', 'make', 'model', 'trim', 'body', 'transmission', 'vin', 'state',
       'condition', 'odometer', 'color', 'interior', 'seller', 'mmr',
       'sellingprice', 'saledate'],
      dtype='object')

In [213]:
# Rename the Columns

df.rename({
    "year":"MFG_Year",
    "make":"Brand",
    "model":"Model",
    "trim":"Designation",
    "body":"Body_Type",
    "transmission":"Transmission",
    "vin":"Vehicle_id",
    "state":"State",
    "condition":"Condition",
"odometer":"Odometer_reading",
"color":"Exterior_color",
"interior":"Interior_Color",
"seller":"Seller",
"mmr":"MMR",
"sellingprice":"Selling_price",
"saledate":"sale_date"}, axis = 1,inplace = True)

In [214]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   MFG_Year          558837 non-null  int64
 1   Brand             548536 non-null  object
 2   Model             548438 non-null  object
 3   Designation       548186 non-null  object
 4   Body_Type         545642 non-null  object
 5   Transmission      493485 non-null  object
 6   Vehicle_id        558833 non-null  object
 7   State             558837 non-null  object
 8   Condition         547017 non-null  float64
 9   Odometer_reading  558743 non-null  float64
 10  Exterior_color    558088 non-null  object
 11  Interior_Color    558088 non-null  object
 12  Seller            558837 non-null  object
 13  MMR               558799 non-null  float64
 14  Selling_price     558825 non-null  float64
 15  sale_date         558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [215]:
# Checking for duplicates

df.duplicated().sum()

np.int64(0)

In [216]:
# Checking for missing or null values

df.isna().sum()

MFG_Year                0
Brand               10301
Model               10399
Designation         10651
Body_Type           13195
Transmission        65352
Vehicle_id              4
State                   0
Condition           11820
Odometer_reading       94
Exterior_color        749
Interior_Color        749
Seller                  0
MMR                    38
Selling_price          12
sale_date              12
dtype: int64

In [217]:
# Drop irrelavant columns

df.drop("Vehicle_id",axis = 1,inplace = True)

In [218]:
df.isna().sum()

MFG_Year                0
Brand               10301
Model               10399
Designation         10651
Body_Type           13195
Transmission        65352
State                   0
Condition           11820
Odometer_reading       94
Exterior_color        749
Interior_Color        749
Seller                  0
MMR                    38
Selling_price          12
sale_date              12
dtype: int64

In [219]:
df["Transmission"].unique()

array(['automatic', nan, 'manual', 'Sedan', 'sedan'], dtype=object)

In [220]:
df["Transmission"].value_counts()

Transmission
automatic    475915
manual        17544
sedan            15
Sedan            11
Name: count, dtype: int64

In [221]:
# Drop "Sedan" and "sedan" values as they are very less in no. of values compared to size of data

df.drop(df[df["Transmission"]=="Sedan"].index, inplace=True)

df.drop(df[df["Transmission"]=="sedan"].index, inplace=True)

In [222]:
df["Transmission"].value_counts()

Transmission
automatic    475915
manual        17544
Name: count, dtype: int64

In [223]:
df["Transmission"].unique()

array(['automatic', nan, 'manual'], dtype=object)

In [224]:
# Fill missing values in "Transmission" Column

df["Transmission"].fillna("unknown",inplace = True)

In [225]:
df["Transmission"].unique()

array(['automatic', 'unknown', 'manual'], dtype=object)

In [226]:
df["Transmission"].isna().sum()

np.int64(0)

In [227]:
df.isna().sum()

MFG_Year                0
Brand               10301
Model               10399
Designation         10651
Body_Type           13195
Transmission            0
State                   0
Condition           11794
Odometer_reading       94
Exterior_color        749
Interior_Color        749
Seller                  0
MMR                    12
Selling_price          12
sale_date              12
dtype: int64

In [228]:
df["Body_Type"].value_counts()

Body_Type
Sedan          199437
SUV            119292
sedan           41906
suv             24552
Hatchback       21380
                ...
g37 coupe           1
cab plus 4          1
CTS-V Wagon         1
Ram Van             1
cts wagon           1
Name: count, Length: 86, dtype: int64

In [229]:
df["Body_Type"].unique()

array(['SUV', 'Sedan', 'Convertible', 'Coupe', 'Wagon', 'Hatchback',
       'Crew Cab', 'G Coupe', 'G Sedan', 'Elantra Coupe', 'Genesis Coupe',
       'Minivan', nan, 'Van', 'Double Cab', 'CrewMax Cab', 'Access Cab',
       'King Cab', 'SuperCrew', 'CTS Coupe', 'Extended Cab',
       'E-Series Van', 'SuperCab', 'Regular Cab', 'G Convertible', 'Koup',
       'Quad Cab', 'CTS-V Coupe', 'sedan', 'G37 Convertible', 'Club Cab',
       'Xtracab', 'Q60 Convertible', 'CTS Wagon', 'convertible',
       'G37 Coupe', 'Mega Cab', 'Cab Plus 4', 'Q60 Coupe', 'Cab Plus',
       'Beetle Convertible', 'TSX Sport Wagon', 'Promaster Cargo Van',
       'GranTurismo Convertible', 'CTS-V Wagon', 'Ram Van', 'minivan',
       'suv', 'Transit Van', 'van', 'regular-cab', 'g sedan', 'g coupe',
       'hatchback', 'king cab', 'supercrew', 'g convertible', 'coupe',
       'crew cab', 'wagon', 'double cab', 'e-series van', 'regular cab',
       'quad cab', 'g37 convertible', 'supercab', 'extended cab',
       'crewmax cab', 'genesis coupe', 'access cab', 'mega cab',
       'xtracab', 'beetle convertible', 'cts coupe', 'koup', 'club cab',
       'elantra coupe', 'q60 coupe', 'cts-v coupe', 'transit van',
       'granturismo convertible', 'tsx sport wagon',
       'promaster cargo van', 'q60 convertible', 'g37 coupe',
       'cab plus 4', 'cts wagon'], dtype=object)

In [230]:
df["Body_Type"] = df["Body_Type"].str.lower()

In [231]:
df["Body_Type"].unique()

array(['suv', 'sedan', 'convertible', 'coupe', 'wagon', 'hatchback',
       'crew cab', 'g coupe', 'g sedan', 'elantra coupe', 'genesis coupe',
       'minivan', nan, 'van', 'double cab', 'crewmax cab', 'access cab',
       'king cab', 'supercrew', 'cts coupe', 'extended cab',
       'e-series van', 'supercab', 'regular cab', 'g convertible', 'koup',
       'quad cab', 'cts-v coupe', 'g37 convertible', 'club cab',
       'xtracab', 'q60 convertible', 'cts wagon', 'g37 coupe', 'mega cab',
       'cab plus 4', 'q60 coupe', 'cab plus', 'beetle convertible',
       'tsx sport wagon', 'promaster cargo van',
       'granturismo convertible', 'cts-v wagon', 'ram van', 'transit van',
       'regular-cab'], dtype=object)

In [232]:
# Replacing incorrect values

df["Body_Type"].replace({
    
    "g sedan": "sedan",
    
    "g convertible": "convertible",
    "g37 convertible": "convertible",
    "q60 convertible": "convertible",
    "beetle convertible": "convertible",
    "granturismo convertible": "convertible",

    "g coupe": "coupe",
    "g37 coupe": "coupe",
    "q60 coupe": "coupe",
    "genesis coupe": "coupe",
    "elantra coupe": "coupe",
    "cts coupe": "coupe",
    "cts-v coupe": "coupe",
    "koup": "coupe",

    "cts wagon": "wagon",
    "cts-v wagon": "wagon",
    "tsx sport wagon": "wagon",

    "crew cab": "cab",
    "double cab": "cab",
    "crewmax cab": "cab",
    "access cab": "cab",
    "king cab": "cab",
    "extended cab": "cab",
    "supercab": "cab",
    "regular cab": "cab",
    "quad cab": "cab",
    "club cab" : "cab",
    "xtracab": "cab",
    "mega cab": "cab",
    "cab plus 4": "cab",
    "cab plus": "cab",
    "regular-cab": "cab",
    "supercrew": "cab",

    "minivan" : "van",
    "e-series van" : "van",
    "promaster cargo van" : "van",
    "ram van": "van",
    "transit van" : "van",
}, inplace=True)

In [233]:
df["Body_Type"].unique()

array(['suv', 'sedan', 'convertible', 'coupe', 'wagon', 'hatchback',
       'cab', 'van', nan], dtype=object)

In [234]:
# Fill missing values in "Body_Type" Column

df["Body_Type"].fillna("unknown",inplace = True)

In [235]:
df["Body_Type"].isna().sum()

np.int64(0)

In [236]:
df.isna().sum()

MFG_Year                0
Brand               10301
Model               10399
Designation         10651
Body_Type               0
Transmission            0
State                   0
Condition           11794
Odometer_reading       94
Exterior_color        749
Interior_Color        749
Seller                  0
MMR                    12
Selling_price          12
sale_date              12
dtype: int64

In [237]:
df["Condition"].unique()

array([ 5., 45., 41., 43.,  1., 34.,  2., 42.,  3., 48., nan, 49., 17.,
       19., 29., 38., 44., 47., 32.,  4., 25., 37., 39., 31., 28., 46.,
       36., 35., 26., 21., 22., 27., 24., 33., 23., 15., 16., 18., 12.,
       14., 11., 13.])

In [238]:
df["Condition"].max()

49.0

In [239]:
# Fill missing values in "Condition" Column

mode = df["Condition"].mode()[0]
df["Condition"].fillna(mode,inplace = True)

In [240]:
df["Condition"].isna().sum()

np.int64(0)

In [241]:
df.isna().sum()

MFG_Year                0
Brand               10301
Model               10399
Designation         10651
Body_Type               0
Transmission            0
State                   0
Condition               0
Odometer_reading       94
Exterior_color        749
Interior_Color        749
Seller                  0
MMR                    12
Selling_price          12
sale_date              12
dtype: int64

In [242]:
df[df["Brand"].isna()]

,MFG_Year,Brand,Model,Designation,Body_Type,Transmission,State,Condition,Odometer_reading,Exterior_color,Interior_Color,Seller,MMR,Selling_price,sale_date
742,2012,NaN,NaN,NaN,unknown,automatic,ca,38.0,23208.0,gray,black,financial services remarketing (lease),47200.0,46000.0,Thu Feb 26 2015 04:30:00 GMT-0800 (PST)
747,2012,NaN,NaN,NaN,unknown,automatic,ca,33.0,19785.0,beige,gray,financial services remarketing (lease),49500.0,46000.0,Thu Feb 12 2015 04:30:00 GMT-0800 (PST)
766,2012,NaN,NaN,NaN,unknown,automatic,ca,37.0,48424.0,black,black,financial services remarketing (lease),42300.0,43000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
798,2012,NaN,NaN,NaN,unknown,automatic,ca,48.0,39825.0,—,gray,financial services remarketing (lease),58100.0,58500.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
803,2012,NaN,NaN,NaN,unknown,automatic,ca,49.0,35093.0,blue,tan,financial services remarketing (lease),45200.0,44500.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558545,2000,NaN,NaN,NaN,unknown,automatic,ma,31.0,108900.0,green,gray,boch toyota/scion south,1275.0,1100.0,Thu Jun 18 2015 11:30:00 GMT-0700 (PDT)
558617,2007,NaN,NaN,NaN,unknown,automatic,pa,41.0,66393.0,—,beige,r hollenshead auto sales inc,18150.0,18500.0,Fri Jun 19 2015 02:00:00 GMT-0700 (PDT)
558736,2011,NaN,NaN,NaN,unknown,automatic,nv,41.0,67820.0,silver,black,imperial rides,9175.0,10500.0,Fri Jun 19 2015 05:00:00 GMT-0700 (PDT)
558773,2005,NaN,NaN,NaN,unknown,automatic,tx,24.0,114787.0,burgundy,black,hopper motorplex inc,15400.0,14800.0,Wed Jun 24 2015 03:15:00 GMT-0700 (PDT)
558776,2013,NaN,NaN,NaN,unknown,automatic,ga,42.0,30148.0,off-white,black,maserati north america inc,58500.0,47000.0,Wed Jun 24 2015 03:00:00 GMT-0700 (PDT)

In [243]:
# Drop missing values in "Brand" Columns

df.dropna(subset = ["Brand"],how="all",inplace = True)

In [244]:
df["Brand"].isna().sum()

np.int64(0)

In [245]:
df.isna().sum()

MFG_Year              0
Brand                 0
Model                98
Designation         350
Body_Type             0
Transmission          0
State                 0
Condition             0
Odometer_reading     90
Exterior_color      734
Interior_Color      734
Seller                0
MMR                  12
Selling_price        12
sale_date            12
dtype: int64

In [246]:
df[df["Model"].isna()]

,MFG_Year,Brand,Model,Designation,Body_Type,Transmission,State,Condition,Odometer_reading,Exterior_color,Interior_Color,Seller,MMR,Selling_price,sale_date
72,2014,BMW,NaN,750Li,sedan,automatic,ca,43.0,12172.0,black,black,financial services remarketing (lease),67000.0,66000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
31262,2014,BMW,NaN,750i,sedan,automatic,ga,44.0,4488.0,silver,black,global imports,67000.0,64200.0,Thu Dec 18 2014 10:00:00 GMT-0800 (PST)
61951,2014,BMW,NaN,750Li xDrive,sedan,automatic,oh,48.0,387.0,black,black,bmw na manheim new jersey,72000.0,72500.0,Tue Dec 30 2014 14:00:00 GMT-0800 (PST)
61955,2014,BMW,NaN,750Li xDrive,sedan,automatic,oh,46.0,414.0,white,—,bmw na manheim new jersey,72000.0,68500.0,Tue Dec 30 2014 14:00:00 GMT-0800 (PST)
61956,2014,BMW,NaN,750i,sedan,automatic,oh,48.0,4796.0,NaN,NaN,bmw north america raa,66000.0,75000.0,Tue Dec 30 2014 14:00:00 GMT-0800 (PST)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546744,2014,BMW,NaN,750Li xDrive,sedan,automatic,oh,38.0,7394.0,black,black,bmw north america raa,60000.0,56000.0,Tue Jun 16 2015 07:00:00 GMT-0700 (PDT)
549010,2014,BMW,NaN,750Li xDrive,sedan,automatic,oh,44.0,943.0,blue,tan,bmw north america greer,64000.0,64500.0,Tue Jun 16 2015 07:00:00 GMT-0700 (PDT)
549011,2014,BMW,NaN,750Li,sedan,automatic,oh,4.0,12895.0,white,black,bmw north america greer,55200.0,57500.0,Tue Jun 16 2015 07:00:00 GMT-0700 (PDT)
552124,2015,Audi,NaN,2.0 TFSI Premium quattro,sedan,automatic,tx,35.0,4529.0,gray,black,tdaf remarketing,26500.0,27000.0,Wed Jun 17 2015 03:15:00 GMT-0700 (PDT)
553665,2015,Audi,NaN,2.0 TFSI Premium quattro,sedan,automatic,ca,4.0,721.0,black,black,audi san diego,26800.0,27000.0,Thu Jun 18 2015 05:30:00 GMT-0700 (PDT)

In [247]:
# Fill missing values in "Model" Column

df["Model"].fillna("unknown",inplace = True)

In [248]:
df["Model"].isna().sum()

np.int64(0)

In [249]:
df.isna().sum()

MFG_Year              0
Brand                 0
Model                 0
Designation         350
Body_Type             0
Transmission          0
State                 0
Condition             0
Odometer_reading     90
Exterior_color      734
Interior_Color      734
Seller                0
MMR                  12
Selling_price        12
sale_date            12
dtype: int64

In [250]:
# Fill missing values in "Designation" Column

df["Designation"].fillna("unknown",inplace = True)

In [251]:
df.isna().sum()

MFG_Year              0
Brand                 0
Model                 0
Designation           0
Body_Type             0
Transmission          0
State                 0
Condition             0
Odometer_reading     90
Exterior_color      734
Interior_Color      734
Seller                0
MMR                  12
Selling_price        12
sale_date            12
dtype: int64

In [252]:
mode_odo = df["Odometer_reading"].mode()[0]

In [253]:
# Fill missing values in "Odometer_reading" Column

df["Odometer_reading"].fillna(mode_odo,inplace = True)

In [254]:
df.isna().sum()

MFG_Year              0
Brand                 0
Model                 0
Designation           0
Body_Type             0
Transmission          0
State                 0
Condition             0
Odometer_reading      0
Exterior_color      734
Interior_Color      734
Seller                0
MMR                  12
Selling_price        12
sale_date            12
dtype: int64

In [255]:
df.dropna(subset = ["Exterior_color"],inplace = True)
df.dropna(subset = ["Interior_Color"],inplace = True)
df.dropna(subset = ["MMR"],inplace = True)
df.dropna(subset = ["Selling_price"],inplace = True)
df.dropna(subset = ["sale_date"],inplace = True)

In [256]:
df.isna().sum()

MFG_Year            0
Brand               0
Model               0
Designation         0
Body_Type           0
Transmission        0
State               0
Condition           0
Odometer_reading    0
Exterior_color      0
Interior_Color      0
Seller              0
MMR                 0
Selling_price       0
sale_date           0
dtype: int64

In [257]:
df.duplicated().sum()

np.int64(0)

In [258]:
df.dtypes

MFG_Year              int64
Brand                object
Model                object
Designation          object
Body_Type            object
Transmission         object
State                object
Condition           float64
Odometer_reading    float64
Exterior_color       object
Interior_Color       object
Seller               object
MMR                 float64
Selling_price       float64
sale_date            object
dtype: object

In [259]:
df["Condition"] =  df["Condition"].astype(int)
df["Condition"].dtype

dtype('int64')

In [260]:
df["sale_date"] = pd.to_datetime(df["sale_date"],utc=True)

In [261]:
df["sale_date"].dtype

datetime64[ns, UTC]

In [262]:
# Decomposing Sale Date into its components

df["sale_year"] = df["sale_date"].dt.year
df["sale_month"] = df["sale_date"].dt.month
df["sale_day"] = df["sale_date"].dt.day
df["sale_time"] = df["sale_date"].dt.time

In [263]:
df.dtypes

MFG_Year                          int64
Brand                            object
Model                            object
Designation                      object
Body_Type                        object
Transmission                     object
State                            object
Condition                         int64
Odometer_reading                float64
Exterior_color                   object
Interior_Color                   object
Seller                           object
MMR                             float64
Selling_price                   float64
sale_date           datetime64[ns, UTC]
sale_year                         int32
sale_month                        int32
sale_day                          int32
sale_time                        object
dtype: object

In [264]:
df.head()

,MFG_Year,Brand,Model,Designation,Body_Type,Transmission,State,Condition,Odometer_reading,Exterior_color,Interior_Color,Seller,MMR,Selling_price,sale_date,sale_year,sale_month,sale_day,sale_time
0,2015,Kia,Sorento,LX,suv,automatic,ca,5,16639.0,white,black,kia motors america inc,20500.0,21500.0,2014-12-16 04:30:00+00:00,2014,12,16,04:30:00
1,2015,Kia,Sorento,LX,suv,automatic,ca,5,9393.0,white,beige,kia motors america inc,20800.0,21500.0,2014-12-16 04:30:00+00:00,2014,12,16,04:30:00
2,2014,BMW,3 Series,328i SULEV,sedan,automatic,ca,45,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,2015-01-14 20:30:00+00:00,2015,1,14,20:30:00
3,2015,Volvo,S60,T5,sedan,automatic,ca,41,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,2015-01-28 20:30:00+00:00,2015,1,28,20:30:00
4,2014,BMW,6 Series Gran Coupe,650i,sedan,automatic,ca,43,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,2014-12-18 04:30:00+00:00,2014,12,18,04:30:00

In [265]:
df[df["MFG_Year"] > df["sale_year"]]

,MFG_Year,Brand,Model,Designation,Body_Type,Transmission,State,Condition,Odometer_reading,Exterior_color,Interior_Color,Seller,MMR,Selling_price,sale_date,sale_year,sale_month,sale_day,sale_time
0,2015,Kia,Sorento,LX,suv,automatic,ca,5,16639.0,white,black,kia motors america inc,20500.0,21500.0,2014-12-16 04:30:00+00:00,2014,12,16,04:30:00
1,2015,Kia,Sorento,LX,suv,automatic,ca,5,9393.0,white,beige,kia motors america inc,20800.0,21500.0,2014-12-16 04:30:00+00:00,2014,12,16,04:30:00
5,2015,Nissan,Altima,2.5 S,sedan,automatic,ca,1,5554.0,gray,black,enterprise vehicle exchange / tra / rental / t...,15350.0,10900.0,2014-12-30 04:00:00+00:00,2014,12,30,04:00:00
11,2015,Kia,Optima,LX,sedan,automatic,ca,48,2034.0,red,tan,kia motors finance,15150.0,17700.0,2014-12-16 04:00:00+00:00,2014,12,16,04:00:00
13,2015,Kia,Sorento,LX,suv,automatic,ca,5,14634.0,silver,black,kia motors america inc,20600.0,21500.0,2014-12-16 04:30:00+00:00,2014,12,16,04:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69268,2015,Nissan,Altima,2.5 S,sedan,unknown,pa,1,9399.0,red,black,enterprise veh exchange/rental,14950.0,3600.0,2014-12-30 02:45:00+00:00,2014,12,30,02:45:00
70513,2015,Chevrolet,Tahoe,LTZ,suv,automatic,ne,41,6018.0,white,tan,husker auto group inc,55700.0,54600.0,2014-12-31 03:00:00+00:00,2014,12,31,03:00:00
70515,2015,Chrysler,200,Limited,sedan,automatic,in,2,73.0,gray,tan,enterprise vehicle exchange / tra / rental / t...,16050.0,6600.0,2014-12-31 04:59:00+00:00,2014,12,31,04:59:00
73093,2015,Ford,Fusion,SE,sedan,automatic,tx,5,3427.0,white,black,rlb investments,13700.0,16300.0,2014-12-31 02:20:00+00:00,2014,12,31,02:20:00
73094,2015,Hyundai,Sonata,SE,sedan,automatic,ca,1,9622.0,black,—,enterprise vehicle exchange / tra / rental / t...,15450.0,8900.0,2014-12-31 07:05:00+00:00,2014,12,31,07:05:00

In [266]:
(df["MFG_Year"] > df["sale_year"]).sum()

np.int64(201)

In [267]:
df.replace(df[df["MFG_Year"] > df["sale_year"]].index, inplace=True)

In [268]:
(df["MFG_Year"] > df["sale_year"]).sum()

np.int64(201)

In [269]:
df["Brand"].unique()

array(['Kia', 'BMW', 'Volvo', 'Nissan', 'Chevrolet', 'Audi', 'Ford',
       'Hyundai', 'Buick', 'Cadillac', 'Acura', 'Lexus', 'Infiniti',
       'Jeep', 'Mercedes-Benz', 'Mitsubishi', 'Mazda', 'MINI',
       'Land Rover', 'Lincoln', 'lincoln', 'Jaguar', 'Volkswagen',
       'Toyota', 'Subaru', 'Scion', 'Porsche', 'bmw', 'Dodge', 'FIAT',
       'Chrysler', 'ford', 'Ferrari', 'Honda', 'GMC', 'mitsubishi', 'Ram',
       'smart', 'chevrolet', 'Bentley', 'chrysler', 'pontiac', 'Pontiac',
       'Saturn', 'Maserati', 'Mercury', 'HUMMER', 'landrover', 'cadillac',
       'land rover', 'mercedes', 'mazda', 'toyota', 'lexus', 'gmc truck',
       'honda', 'nissan', 'porsche', 'Saab', 'Suzuki', 'dodge', 'subaru',
       'Oldsmobile', 'oldsmobile', 'hyundai', 'jeep', 'Isuzu', 'dodge tk',
       'Geo', 'acura', 'volkswagen', 'suzuki', 'kia', 'audi',
       'Rolls-Royce', 'gmc', 'maserati', 'mazda tk', 'mercury', 'buick',
       'hyundai tk', 'mercedes-b', 'vw', 'Daewoo', 'chev truck',
       'ford tk', 'plymouth', 'Plymouth', 'ford truck', 'Tesla',
       'airstream', 'dot', 'Aston Martin', 'Fisker', 'Lamborghini',
       'Lotus'], dtype=object)

In [270]:
df["Brand"] = df["Brand"].str.capitalize()

In [271]:
df["Brand"].unique()

array(['Kia', 'Bmw', 'Volvo', 'Nissan', 'Chevrolet', 'Audi', 'Ford',
       'Hyundai', 'Buick', 'Cadillac', 'Acura', 'Lexus', 'Infiniti',
       'Jeep', 'Mercedes-benz', 'Mitsubishi', 'Mazda', 'Mini',
       'Land rover', 'Lincoln', 'Jaguar', 'Volkswagen', 'Toyota',
       'Subaru', 'Scion', 'Porsche', 'Dodge', 'Fiat', 'Chrysler',
       'Ferrari', 'Honda', 'Gmc', 'Ram', 'Smart', 'Bentley', 'Pontiac',
       'Saturn', 'Maserati', 'Mercury', 'Hummer', 'Landrover', 'Mercedes',
       'Gmc truck', 'Saab', 'Suzuki', 'Oldsmobile', 'Isuzu', 'Dodge tk',
       'Geo', 'Rolls-royce', 'Mazda tk', 'Hyundai tk', 'Mercedes-b', 'Vw',
       'Daewoo', 'Chev truck', 'Ford tk', 'Plymouth', 'Ford truck',
       'Tesla', 'Airstream', 'Dot', 'Aston martin', 'Fisker',
       'Lamborghini', 'Lotus'], dtype=object)

In [272]:
df["Brand"].replace({

    "Landrover": "Land Rover",
    "Land rover": "Land Rover",

    "Mercedes-b": "Mercedes",

    "Vw": "Volkswagen",

    "Gmc truck": "Gmc",
    "Chev truck": "Chevrolet",
    "Ford truck": "Ford",
    "Ford tk": "Ford",
    "Mazda tk": "Mazda",
    "Hyundai tk": "Hyundai",
    "Dodge tk": "Dodge"
}
,inplace = True)

In [273]:
df["Brand"].unique()

array(['Kia', 'Bmw', 'Volvo', 'Nissan', 'Chevrolet', 'Audi', 'Ford',
       'Hyundai', 'Buick', 'Cadillac', 'Acura', 'Lexus', 'Infiniti',
       'Jeep', 'Mercedes-benz', 'Mitsubishi', 'Mazda', 'Mini',
       'Land Rover', 'Lincoln', 'Jaguar', 'Volkswagen', 'Toyota',
       'Subaru', 'Scion', 'Porsche', 'Dodge', 'Fiat', 'Chrysler',
       'Ferrari', 'Honda', 'Gmc', 'Ram', 'Smart', 'Bentley', 'Pontiac',
       'Saturn', 'Maserati', 'Mercury', 'Hummer', 'Mercedes', 'Saab',
       'Suzuki', 'Oldsmobile', 'Isuzu', 'Geo', 'Rolls-royce', 'Daewoo',
       'Plymouth', 'Tesla', 'Airstream', 'Dot', 'Aston martin', 'Fisker',
       'Lamborghini', 'Lotus'], dtype=object)

In [274]:
df["State"].unique()

array(['ca', 'tx', 'pa', 'mn', 'az', 'wi', 'tn', 'md', 'fl', 'ne', 'nj',
       'nv', 'oh', 'mi', 'ga', 'va', 'sc', 'nc', 'in', 'il', 'co', 'ut',
       'mo', 'ny', 'ma', 'pr', 'or', 'la', 'wa', 'hi', 'qc', 'ab', 'on',
       'ok', 'ms', 'nm', 'al', 'ns'], dtype=object)

In [275]:
df["Designation"].unique()

array(['LX', '328i SULEV', 'T5', ..., 'pure', 'EWB', 'Power Wagon'],
      shape=(1962,), dtype=object)

In [276]:
df["MMR"].unique()

array([ 20500.,  20800.,  31900., ..., 182000., 119000., 164000.],
      shape=(1097,))

In [277]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 547764 entries, 0 to 558836
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   MFG_Year          547764 non-null  int64
 1   Brand             547764 non-null  object
 2   Model             547764 non-null  object
 3   Designation       547764 non-null  object
 4   Body_Type         547764 non-null  object
 5   Transmission      547764 non-null  object
 6   State             547764 non-null  object
 7   Condition         547764 non-null  int64
 8   Odometer_reading  547764 non-null  float64
 9   Exterior_color    547764 non-null  object
 10  Interior_Color    547764 non-null  object
 11  Seller            547764 non-null  object
 12  MMR               547764 non-null  float64
 13  Selling_price     547764 non-null  float64
 14  sale_date         547764 non-null  datetime64[ns, UTC]
 15  sale_year         547764 non-null  int32
 16  sale_month        547764 non-null  int32
 17  sale_day          547764 non-null  int32
 18  sale_time         547764 non-null  object
dtypes: datetime64[ns, UTC](1), float64(3), int32(3), int64(2), object(10)
memory usage: 77.3+ MB

In [278]:
df.isna().sum()

MFG_Year            0
Brand               0
Model               0
Designation         0
Body_Type           0
Transmission        0
State               0
Condition           0
Odometer_reading    0
Exterior_color      0
Interior_Color      0
Seller              0
MMR                 0
Selling_price       0
sale_date           0
sale_year           0
sale_month          0
sale_day            0
sale_time           0
dtype: int64

In [279]:
df.describe()

,MFG_Year,Condition,Odometer_reading,MMR,Selling_price,sale_year,sale_month,sale_day
count,547764.000000,547764.000000,547764.000000,547764.000000,547764.000000,547764.000000,547764.000000,547764.000000
mean,2010.113410,29.754734,67860.095746,13841.348875,13684.622600,2014.902334,4.491405,14.743981
std,3.908894,13.272485,52962.790798,9629.429574,9703.738148,0.296863,3.328541,8.803376
min,1984.000000,2.000000,2.000000,75.000000,100.000000,2014.000000,2.000000,2.000000
25%,2008.000000,21.000000,28325.000000,7275.000000,7000.000000,2015.000000,2.000000,7.000000
50%,2012.000000,33.000000,51736.500000,12350.000000,12200.000000,2015.000000,3.000000,17.000000
75%,2013.000000,39.000000,98289.250000,18350.000000,18250.000000,2015.000000,6.000000,21.000000
max,2015.000000,48.000000,999999.000000,182000.000000,230000.000000,2015.000000,12.000000,31.000000

In [280]:
# Saving the cleaned data set

df.to_csv("cleaned_car_prices.csv", index=False)